### ISSUE TITLE
Not able to build using vs2017

### ISSUE THREAD

**Issue by swanandb2** [Yucked/Ankh#1]

**Comment by Yucked** [comment]
does vs2017 support .net 8?

**Comment by swanandb2** [comment]
Yes, I upgrade to VS2022 and It uses .net8, can you please help me with exact steps how to build this app?
I am new in C#, Do we need to install any additional framework?
[Err.txt](https://github.com/Yucked/Ankh/files/15366454/Err.txt)
![image](https://github.com/Yucked/Ankh/assets/34519576/59ef931c-456b-4c94-88f2-ba351472b7b1)
![image](https://github.com/Yucked/Ankh/assets/34519576/030c432f-5ac5-4084-a30d-a8a8497e95bf)

**Comment by Yucked** [comment]
You can't build the Ankh.csproj but Ankh.API is buildable

**Comment by Fincke** [comment]
Can't build Ankh.API, complains about Redis. Which output did you use?

**Comment by Yucked** [comment]
Sorry dude there are still changes being pushed out so its not stable

**Comment by Fincke** [comment]
Can I contact you?

**Comment by swanandb2** [comment]
Yes you can connect me anytime.
